name: push-main

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Get dependencies
      run: npm install
    - name: Run Test
      run: npm test
    - name: Run ESLint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Notify to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,took,workflow,job,ref,message
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
